name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --include-workspace-root --workspaces

      - name: Install Playwright browsers
        run: |
          cd packages/e2e
          npx playwright install chromium

      - name: Build frontend app
        run: |
          cd apps/frontend
          npm run build

      - name: Start frontend server
        run: |
          cd apps/frontend
          npm run start &
          # Wait for server to be ready
          sleep 10
          # Check if server is responding
          curl -f http://localhost:3000 || (echo "Server failed to start" && exit 1)
        env:
          NODE_ENV: production

      - name: Run E2E tests against local server
        run: |
          echo "Testing against URL: $PLAYWRIGHT_BASE_URL"
          cd packages/e2e
          npm test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30 